esiaf_input_topic: /input
esiaf_output_topic: /esiaf_ros/ssled
algorithm: SRP # one of ['MUSIC', 'SRP', 'CSSM', 'WAVES', 'TOPS', 'FRIDA']
mic_array:
    channel_1:
        x: -0.0267
        y: 0.0343
    channel_2:
        x: -0.0267
        y: -0.0343
    channel_3:
        x: 0.0313
        y: 0.0343
    channel_4:
        x: 0.0313
        y: -0.0343